config/routes.rb
Rails.application.routes.draw do
  resources :decors
  resources :equipment
  resources :schools
  resources :aquaria
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/', to: 'application#homepage'
  get '/contact', to: 'application#contact'
  get '/resources', to: 'application#resources'
end

app/controllers/aquaria_controller.rb
class AquariaController < ApplicationController

  before_action :find_aquarium, only: [:update]

  def index
      @aquaria = Aquarium.all
      @fish_urls = ["https://i.imgur.com/KYqnjHh.png",
      "https://www.aqueon.com/-/media/images/aqueon-na/us/assets/care-sheets/tigerbarborsumatrabarbfish_600x400%20png.png?h=400&la=en&w=600&hash=209E3AC3907BBC855E4F98576BC3DB2326E5673B",
      "https://png2.kisspng.com/sh/9ff6c4054d98a0376063b08a79d8f43b/L0KzQYm3VME6N5p5j5H0aYP2gLBuTfdwdJVrgeVxLXH0hbL5igVue15shNHvaYPrPcXslQJiNZD3edDwZT3qfLFATcVibGo1fNRsNnS1QLe6TsIxQWIASKk7MUW1RIKAVMI3QGU5T5D5bne=/kisspng-goldfish-aquariums-glofish-tetra-orange-glow-5ad90dbc6d20f3.209190721524174268447.png",
      "https://i.imgur.com/V8iLmgd.png",
      "https://i.imgur.com/LRGNULI.png",
      "https://i.imgur.com/FNjPmM2.png",
      "https://i.imgur.com/0LAKanv.png",
      "https://i.imgur.com/r7CW4Vz.png",
      "https://i.imgur.com/yg7A7R9.png",
      "https://png2.kisspng.com/sh/63aefe613530b195ca1fea92cc8223a8/L0KzQYm3WMEyN5ZwkJH0aYP2gLBuTgBwc550hp9DLXHxdH7CTfd6aaNmfNH8LYDye772jr1od15yedlya3H1gH70igMuNWZnTtgCZki4dIa8V8k2Nmo1Sqg8MEC6QYa6VMA0O2gAT6oCM0mxgLBu/kisspng-pokmon-x-and-y-gyarados-pokmon-go-magikarp-mis--5b6f7f85d55795.9026300715340337978739.png"
    ]
  end

  def new
    @aquarium = Aquarium.new
    @tanks = [10, 55]
  end

  def show
    @aquarium = Aquarium.all.last
  end

  def create
    @aquarium = Aquarium.create(aquarium_params)
    redirect_to new_school_path
  end

  def edit
    @aquarium = Aquarium.all.last
    @tanks = [10, 55]
  end

  def update
   @aquarium.update(aquarium_params)
   redirect_to aquarium_path(@aquarium)
 end

 private

  def aquarium_params
    params.require(:aquarium).permit(:creator, :gallons)
  end

  def find_aquarium
    @aquarium = Aquarium.find_by(id: params[:id])
  end

  @fish_images = ["Neon Tetra", "Tiger Barb", "Glo Fish Tetra", "Swordtail", "Cory Catfish", "Dwarf Gourami", "Molly", "Ram Cichlid", "Magikarp", "Gyarados"]

  @fish_urls = ["https://lh3.googleusercontent.com/psBqrj-YKQsh4O_DvpShA4nbwECXQMC3rgSOJexKaqsyoDnzjiYWAs6HLNb6DRI4CVm7zmqHGZ_EoLUXBpkircQ5yrv2uos1vwmg-M1wFBLMzXPQCExBjrhBbu77QLSrB-RSe3Nemsuj31-SA75oQrzmZ84ZwEevAl5S4pOXQGyTHVO66Tv0ys0L11bMi2Cx-CBYyq9Sat7x629brk7gVAILSMH9sI2M3sQlAJo6BGDXSBT_hPM6f785F2do-tTSRXuNLDyWDd-EPEWsfEZG-1DNCTtq18Z6tU4moQif3NJzE4Ye2Y22z0aIxbGQqhq-Jdc7pM1KIHLHqK0W5aBn_P6nfdmyJaCYCdxcK5JIOFZkza6-jweV257Guyo2NbU128zz0gxf4REKF82edHKRb8Brmukrof-EK0lxEycsUQfewYgwFQO27T41DlVskOYZJgvanFZAAzMcVSAy3AG1ftlU92aYyqiYfVtEWszdwZzG9WD2Mu6qly9TDfHMDoyC6U3uJg9yHJ-d-bCkplOu_AUjimGAZQMJNmbcURA03Y2FRPcz8DopLB_BBj1T4lulBEf36lueEe3oUiVs4UyemVHH7GokGDueefxSN4q3riJNh6NyshRqtL3F7QbkcYZ5KlTIR7SjbHx9UufIx-ToL6w=s250-no"]

end

app/helpers/aquaria_helper.rb
module AquariaHelper
end

app/views/aquaria/_form.erb
<div class="container">
  <%= form_for @aquarium, class: "form" do |f| %>
  <%= f.label :creator, "Your name" %>
  <%= f.text_field :creator  %><br><br>
  <%= f.label :gallons %>
  <%= f.select(:gallons, @tanks)  %><br><br>
  <%= f.submit "Next", :class => 'waves-effect waves-light btn-small orange' %>
  <% end %>
</div>

<img src="https://i.imgur.com/kCCvdka.png" alt="Italian Trulli" class="image animated pulse animations">

app/views/aquaria/edit.erb
<br>
<div class="container"><h5 class="light">Edit Aquarium Size</h5></div>
<br>
<%= render 'form' %>

app/views/aquaria/index.erb
<div class="section container">
  <br>

  <h5 class = "light">Check out other aquaria!</h5>

  <br><br>

  <div class="container">
    <% @aquaria.each do |aq| %>
        <%= link_to aq.creator, aquarium_path(aq)%><br>
    <%end %>
  </div>

<img src="https://i.imgur.com/kCCvdka.png" alt="Italian Trulli" class="image">

app/views/aquaria/new.erb
<br>
<div class="container"><h5 class="light ">Select Aquarium Size</h5></div>
<br>

<%= render 'form' %>

app/views/aquaria/show.erb
<div class="container">

<% fish_images = ["Neon Tetra", "Tiger Barb", "Glo Fish Tetra", "Swordtail", "Cory Catfish", "Dwarf Gourami", "Molly", "Ram Cichlid", "Magikarp", "Gyarados"] %>

<% fish_urls = ["https://i.imgur.com/KYqnjHh.png",

"https://www.aqueon.com/-/media/images/aqueon-na/us/assets/care-sheets/tigerbarborsumatrabarbfish_600x400%20png.png?h=400&la=en&w=600&hash=209E3AC3907BBC855E4F98576BC3DB2326E5673B",

"https://png2.kisspng.com/sh/9ff6c4054d98a0376063b08a79d8f43b/L0KzQYm3VME6N5p5j5H0aYP2gLBuTfdwdJVrgeVxLXH0hbL5igVue15shNHvaYPrPcXslQJiNZD3edDwZT3qfLFATcVibGo1fNRsNnS1QLe6TsIxQWIASKk7MUW1RIKAVMI3QGU5T5D5bne=/kisspng-goldfish-aquariums-glofish-tetra-orange-glow-5ad90dbc6d20f3.209190721524174268447.png",

"https://i.imgur.com/V8iLmgd.png",

"https://i.imgur.com/LRGNULI.png",

"https://i.imgur.com/FNjPmM2.png",

"https://i.imgur.com/0LAKanv.png",

"https://i.imgur.com/r7CW4Vz.png",

"https://i.imgur.com/yg7A7R9.png",

"https://png2.kisspng.com/sh/63aefe613530b195ca1fea92cc8223a8/L0KzQYm3WMEyN5ZwkJH0aYP2gLBuTgBwc550hp9DLXHxdH7CTfd6aaNmfNH8LYDye772jr1od15yedlya3H1gH70igMuNWZnTtgCZki4dIa8V8k2Nmo1Sqg8MEC6QYa6VMA0O2gAT6oCM0mxgLBu/kisspng-pokmon-x-and-y-gyarados-pokmon-go-magikarp-mis--5b6f7f85d55795.9026300715340337978739.png"

] %>

<% img1 = fish_urls[fish_images.index(@aquarium.school.species1)] %>
<% img2 = fish_urls[fish_images.index(@aquarium.school.species2)] %>
<% img3 = fish_urls[fish_images.index(@aquarium.school.species3)] %>
<% img4 = fish_urls[fish_images.index(@aquarium.school.species4)] %>
<% img5 = fish_urls[fish_images.index(@aquarium.school.species5)] %>
<br>
<br>
<div class="container " >

  <div class="parent animated bounceInDown">
    <img class="fish_tank" src="https://cdn.dribbble.com/users/375867/screenshots/1512391/under-the-sea-ocean-water-aquarium-game-background-game-asset-side-scroller.png">

    <div class="tool" data-tip=<%=@aquarium.school.species1 %>><img class="fish1 animated pulse animations" src="<%=img1%>"> </div>
    <div class="tool" data-tip=<%=@aquarium.school.species2 %>><img class="fish2 animated pulse animations" src="<%=img2%>"> </div>
    <div class="tool" data-tip=<%=@aquarium.school.species3 %>><img class="fish3 animated pulse animations" src="<%=img3%>"> </div>
    <div class="tool" data-tip=<%=@aquarium.school.species4 %>><img class="fish4 animated pulse animations" src="<%=img4%>"> </div>
    <div class="tool" data-tip=<%=@aquarium.school.species5 %>><img class="fish5 animated pulse animations" src="<%=img5%>"> </div>

  </div> <br>


  <h5 class = 'light'> <%=@aquarium.creator%>'s Aquarium</h5> <br>

  <p><b>Size</b>: <%= @aquarium.gallons %> gallons </p>
  <p><%= link_to "Edit", edit_aquarium_path %> </p>

  <p><b>Style</b>: <%= @aquarium.decor.style %>< /p>
  <%= link_to "Edit", edit_decor_path %><br>

  <p><b> Fish Facts </b></p>
  <ul>
    <li><b><%=@aquarium.school.species1 %></b>: <%= @aquarium.school.facts1 %></li> <br>
    <li><b><%=@aquarium.school.species2 %></b>: <%= @aquarium.school.facts2 %></li> <br>
    <li><b><%=@aquarium.school.species3 %></b>: <%= @aquarium.school.facts3 %></li> <br>
    <li><b><%=@aquarium.school.species4 %></b>: <%= @aquarium.school.facts4 %></li> <br>
    <li><b><%=@aquarium.school.species5 %></b>: <%= @aquarium.school.facts5 %></li> <br>
  </ul>
  <p><%= link_to "Edit", edit_school_path %></p>

  <p><b> Equipments Facts </b></p>
  <ul>
    <li><b><%=@aquarium.equipment.item1 %></b>: <%= @aquarium.equipment.facts1 %></li><br>
    <li><b><%=@aquarium.equipment.item2 %></b>: <%= @aquarium.equipment.facts2 %></li><br>
    <li><b><%=@aquarium.equipment.item3 %></b>: <%= @aquarium.equipment.facts3 %></li>
  </ul>
  <p><%= link_to "Edit", edit_equipment_path %></p>
</div>